BNB deployment (#40)
This PR contains deployment data for BNB chain.

The contract remains unverified since bscscan still hasn't indexed the
contract properly:

https://bscscan.com/address/0x9da8B48441583a2b93e2eF8213aAD0EC0b392C69#code

Other explorers show the bytecode:

https://www.oklink.com/bsc/address/0x9da8b48441583a2b93e2ef8213aad0ec0b392c69/contract

```shell
$ forge verify-contract --verifier-url https://api.bscscan.com/api --watch --rpc-url "$ETH_RPC_URL" 0x9da8B48441583a2b93e2eF8213aAD0EC0b392C69 FlashLoanRouter --guess-constructor-args
Start verifying contract `0x9da8B48441583a2b93e2eF8213aAD0EC0b392C69` deployed on bsc
Error: Contract was not found: 0x9da8B48441583a2b93e2eF8213aAD0EC0b392C69
```

upd: bcsscan has finally indexed the contract. I verified it manually ✅